### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by Minecon724** [lucasjones/cpuminer-multi#110]
Hey, Kaspersky Free Antivirus thinks cpuminer is a trojan:
PDM:Trojan.Win32.Generic
cpuminer directory\minerd.exe
cpuminer directory\minerd.exe:Zone.Identifier
https://threats.kaspersky.com/en/class/RiskTool/

**Comment by DarrenRainey** [comment]
This is to be expected as lots of malware authors add cpuminer to their software in an effort to make more money.
