### ISSUE TITLE
error: could not find crypto

### ISSUE THREAD

**Issue by cringer** [lucasjones/cpuminer-multi#17]
Trying to compile on Ubuntu 14.10.  When running `./configure CFLAGS="-march=native"` I get an error that states: 

    error: in `/home/jeremys/Sandbox/cpuminer-multi':
    configure: error: could not find crypto

The same error occurs when running `./configure CFLAGS="-O3"`.

**Comment by cringer** [comment]
Also I am using the source files from the cloned repository, not one of the release versions.

**Comment by cringer** [comment]
I was able to determine that this issue was due to not having libssl-dev installed.  Once I performed `sudo apt-get install libssl-dev` running `./configure CFLAGS="-march=native"` worked correctly.

**Comment by Jany-M** [comment]
I can confirm that `yum install openssl-devel` on CentOS 7+, will also fix the issue.
