### ISSUE TITLE
Can't compile in OpenSuse AArch64

### ISSUE THREAD

**Issue by ramonhugo** [lucasjones/cpuminer-multi#54]
I'm trying to compile it using OpenSuse AArch64 with a Raspberry Pi 3.
The architecture seems not to be predicted, and it is trying some default architecture maybe?

The gcc seems ok, and at some point when compiling it returns:

Checking weather the C compiler works ... No

**Comment by tkinjo1985** [comment]
ramonhugo

it worked AArch64.

https://github.com/tkinjo1985/cpuminer-multi

**Comment by ramonhugo** [comment]
I do apologize, the problem was with OpenSuse. The gcc version is not 5, and that's why I was having problems.
