### ISSUE TITLE
Cross Compile For Windows From Debian

### ISSUE THREAD

**Issue by DarrenRainey** [lucasjones/cpuminer-multi#61]
Hello can some help me cross compile this for windows on debian 9 I've tried this https://gist.github.com/erkmos/406a5e4bededd38fd797

as well as compiling gmp with mingw but I can't get cpuminer-multi  to cross compile only the standard pooler cpu miner.

**Comment by DarrenRainey** [comment]
Can someone help me cross compile this please ?

**Comment by ghost** [comment]
I send you a message, i havesuccess to compile this version, but now i'm trying to compile the tpruvot version with more algo, clic here : https://gist.github.com/erkmos/406a5e4bededd38fd797 and read the bottom message and send me an email
