### ISSUE TITLE
Cannot build on OSX

### ISSUE THREAD

**Issue by leukhin** [lucasjones/cpuminer-multi#9]
Can you please provide guide for build binary on OSX. Because autogen.sh missing dependency 
```./autogen.sh: line 8: aclocal: command not found```

**Comment by funboxfilms** [comment]
I'm using Windows 

Jesse Harris 
CEO Moviejump inc.
📱- 6043516575
✉️- Funboxfilms@me.com

**Comment by ghost** [comment]
@denys how did you get past that error when running make?

**Comment by idx3d** [comment]
@adriaanjoubert sorry, but I cannot recall. I believe I just tried instructions, but maybe issue was with my env.
